### ISSUE TITLE
Using URL with React states

### ISSUE THREAD

**Issue by louptheron** [rmariuzzo/react-new-window#108]
Hi,

I would like to use `<NewWindow url="/myapppage" />`, but I can't access the React redux state.
When using childrens of `NewWindow`, my states are set.

Can't we access states when using `url` ?

Thank you!

**Comment by rmariuzzo** [comment]
Hey there! First of all, I really apologize for the long reply.

> Can't we access [redux] states when using url ?

It depends. Yes if you are persisting your state to `localStorage` (which will be shared), otherwise no.
Please note, that persisting state to localStorage can created undesired side effects depending on how you structure you data into it and how your app depends on it.
